#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""M6-A · OpenTelemetry instrumentation for MergePilot.

Provides span creation, context propagation, and redaction for the
Controller → Gateway → Skill → MCP vertical slice.

Design decisions:
- Uses the existing MergePilot correlation IDs (run_id, trace_id,
  correlation_id) as OTel span ATTRIBUTES — not replacing them.
- OTel trace_id/span_id are generated by the SDK; the MergePilot
  trace_id is carried as the ``mp.trace_id`` attribute for correlation
  with the existing DB audit schema.
- Sensitive fields (PATs, tokens, env secrets) are NEVER written to
  span attributes; a denylist is enforced.
- Fail-closed: if OTel export fails, the business logic continues
  (observability must not break the pipeline), but the error is logged
  to stderr and the span is dropped (not retried inline).
- No SLS backend — exports to a local in-memory collector for testing
  and to OTLP HTTP for production (configurable).

Span naming contract (frozen):
  controller.process_event    — wraps the top-level controller event loop
  gateway.call_tool           — wraps each Policy Gateway MCP call
  skill.<skill_name>          — wraps each Skill execution
  mcp.upstream                — wraps each upstream Docker/GitHub API call

Required attributes on ALL spans:
  mp.run_id          — the task run identifier
  mp.trace_id        — the MergePilot internal trace ID (NOT OTel trace_id)
  mp.agent_role      — reviewer | fixer | verifier | coordinator | manager

Conditional attributes (by span type):
  controller: mp.stage, mp.attempt, mp.event_type, mp.verdict
  gateway:    mp.correlation_id, mp.tool, mp.decision, mp.git_sha
  skill:      mp.skill_name, mp.skill_version, mp.request_id, mp.status
  mcp:        mp.correlation_id, mp.endpoint, mp.method, mp.status_code
"""
from __future__ import annotations

import contextlib
import json
import os
import sys
import time
import traceback
from typing import Any, Optional

# ---------------------------------------------------------------------------
# Sensitive-field denylist — NEVER write these to span attributes
# ---------------------------------------------------------------------------

SENSITIVE_KEY_PATTERNS = (
    "token", "secret", "password", "passwd", "pat", "api_key",
    "apikey", "credential", "private_key", "auth_token",
    "authorization", "cookie", "session",
)

SENSITIVE_VALUE_PATTERNS = (
    "ghp_", "ghs_", "gho_", "sk-", "AKIA", "xox",
    "BEGIN RSA PRIVATE", "BEGIN OPENSSH PRIVATE",
)


def _is_sensitive_key(key: str) -> bool:
    kl = key.lower()
    return any(p in kl for p in SENSITIVE_KEY_PATTERNS)


def _is_sensitive_value(value: Any) -> bool:
    if not isinstance(value, str):
        return False
    return any(p in value for p in SENSITIVE_VALUE_PATTERNS)


def redact_attributes(attrs: dict) -> dict:
    """Return a copy of ``attrs`` with sensitive keys/values removed."""
    out = {}
    for k, v in attrs.items():
        if _is_sensitive_key(k):
            out[k] = "<redacted>"
        elif _is_sensitive_value(v):
            out[k] = "<redacted>"
        else:
            out[k] = v
    return out


# ---------------------------------------------------------------------------
# In-memory span collector (for local testing without OTLP backend)
# ---------------------------------------------------------------------------


class SpanRecord:
    """A single recorded span (OTel-compatible shape)."""
    __slots__ = ("trace_id", "span_id", "parent_span_id", "name",
                 "status", "start_time", "end_time", "attributes",
                 "events", "run_id")

    def __init__(self, trace_id, span_id, parent_span_id, name,
                 run_id, attributes=None):
        self.trace_id = trace_id
        self.span_id = span_id
        self.parent_span_id = parent_span_id
        self.name = name
        self.status = "OK"
        self.start_time = time.time()
        self.end_time = None
        self.attributes = redact_attributes(attributes or {})
        self.events = []
        self.run_id = run_id

    def set_attribute(self, key, value):
        if _is_sensitive_key(key) or _is_sensitive_value(value):
            self.attributes[key] = "<redacted>"
        else:
            self.attributes[key] = value

    def add_event(self, name, attributes=None):
        self.events.append({
            "name": name,
            "timestamp": time.time(),
            "attributes": redact_attributes(attributes or {}),
        })

    def set_status(self, status):
        if status not in ("OK", "ERROR", "UNSET"):
            raise ValueError("span status must be OK/ERROR/UNSET")
        self.status = status

    def end(self):
        self.end_time = time.time()

    @property
    def duration_ms(self):
        if self.end_time:
            return round((self.end_time - self.start_time) * 1000, 2)
        return None

    def to_dict(self):
        return {
            "trace_id": self.trace_id,
            "span_id": self.span_id,
            "parent_span_id": self.parent_span_id,
            "name": self.name,
            "status": self.status,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "duration_ms": self.duration_ms,
            "run_id": self.run_id,
            "attributes": dict(self.attributes),
            "events": list(self.events),
        }


class InMemoryCollector:
    """Collects spans in-process for testing. Thread-safe."""

    def __init__(self):
        self.spans = []
        self._lock = __import__("threading").Lock()

    def add_span(self, span: SpanRecord):
        with self._lock:
            self.spans.append(span)

    def clear(self):
        with self._lock:
            self.spans.clear()

    def get_by_run_id(self, run_id):
        with self._lock:
            return [s for s in self.spans if s.run_id == run_id]

    def get_by_name(self, name):
        with self._lock:
            return [s for s in self.spans if s.name == name]

    def to_json(self):
        with self._lock:
            return json.dumps([s.to_dict() for s in self.spans], indent=2)

    @property
    def count(self):
        with self._lock:
            return len(self.spans)


# ---------------------------------------------------------------------------
# Global collector (singleton) — set by tests; None = no collection
# ---------------------------------------------------------------------------

_global_collector: Optional[InMemoryCollector] = None


def set_collector(collector: Optional[InMemoryCollector]):
    global _global_collector
    _global_collector = collector


def get_collector() -> Optional[InMemoryCollector]:
    return _global_collector


# ---------------------------------------------------------------------------
# Span context + tracer
# ---------------------------------------------------------------------------

import hashlib
import random


def _gen_span_id() -> str:
    return hashlib.sha256(os.urandom(16)).hexdigest()[:16]


def _gen_trace_id() -> str:
    return hashlib.sha256(os.urandom(16)).hexdigest()[:32]


class SpanContext:
    """Carries trace_id, span_id, and run_id across the call chain."""
    __slots__ = ("trace_id", "span_id", "run_id")

    def __init__(self, trace_id, span_id, run_id):
        self.trace_id = trace_id
        self.span_id = span_id
        self.run_id = run_id

    def child(self):
        return SpanContext(self.trace_id, _gen_span_id(), self.run_id)


# Thread-local current span context
import threading
_current_ctx = threading.local()


def get_current_context() -> Optional[SpanContext]:
    return getattr(_current_ctx, "ctx", None)


def _set_current_context(ctx: Optional[SpanContext]):
    if ctx is None:
        if hasattr(_current_ctx, "ctx"):
            del _current_ctx.ctx
    else:
        _current_ctx.ctx = ctx


@contextlib.contextmanager
def start_span(name: str, run_id: str = "", trace_id: str = "",
               agent_role: str = "", **attributes):
    """Start a new span as a child of the current context (or root).

    Usage:
        with start_span("controller.process_event",
                        run_id="run-1", trace_id="trace-1",
                        agent_role="coordinator") as span:
            span.set_attribute("mp.stage", "review")
            ...

    The span is automatically ended on context exit. If an exception
    occurs, the span status is set to ERROR and the exception is recorded
    as an event (then re-raised).
    """
    parent = get_current_context()

    if trace_id and parent is None:
        # Root span — use provided trace_id
        ctx = SpanContext(trace_id, _gen_span_id(), run_id)
    elif parent is not None:
        # Child span — inherit trace_id from parent
        ctx = parent.child()
        if run_id and not ctx.run_id:
            ctx.run_id = run_id
    else:
        # No parent, no trace_id — generate both
        ctx = SpanContext(_gen_trace_id(), _gen_span_id(), run_id)

    span = SpanRecord(
        trace_id=ctx.trace_id,
        span_id=ctx.span_id,
        parent_span_id=parent.span_id if parent else None,
        name=name,
        run_id=ctx.run_id,
    )

    # Set required attributes
    if run_id:
        span.set_attribute("mp.run_id", run_id)
    if trace_id or ctx.trace_id:
        span.set_attribute("mp.trace_id", trace_id or ctx.trace_id)
    if agent_role:
        span.set_attribute("mp.agent_role", agent_role)

    # Set extra attributes
    for k, v in attributes.items():
        span.set_attribute(k, v)

    _set_current_context(ctx)
    try:
        yield span
        if span.status == "UNSET":
            span.set_status("OK")
    except Exception as exc:
        span.set_status("ERROR")
        span.add_event("exception", {
            "type": type(exc).__name__,
            "message": str(exc)[:200],
            # NEVER include traceback (may contain secrets in env dumps)
        })
        raise
    finally:
        span.end()
        if _global_collector is not None:
            try:
                _global_collector.add_span(span)
            except Exception:
                pass  # fail-closed: observability must not break pipeline
        _set_current_context(parent)


# ---------------------------------------------------------------------------
# Convenience wrappers for the three required span types
# ---------------------------------------------------------------------------


@contextlib.contextmanager
def controller_span(run_id: str, trace_id: str, agent_role: str = "coordinator",
                    stage: str = "", attempt: int = 0, **kw):
    """Span for controller.process_event (the top-level event loop tick)."""
    attrs = {"mp.stage": stage, "mp.attempt": attempt}
    attrs.update(kw)
    with start_span("controller.process_event", run_id=run_id,
                    trace_id=trace_id, agent_role=agent_role, **attrs) as span:
        yield span


@contextlib.contextmanager
def gateway_span(run_id: str, trace_id: str, correlation_id: str = "",
                 tool: str = "", agent_role: str = "", **kw):
    """Span for gateway.call_tool (each Policy Gateway MCP call)."""
    attrs = {}
    if correlation_id:
        attrs["mp.correlation_id"] = correlation_id
    if tool:
        attrs["mp.tool"] = tool
    attrs.update(kw)
    with start_span("gateway.call_tool", run_id=run_id,
                    trace_id=trace_id, agent_role=agent_role, **attrs) as span:
        yield span


@contextlib.contextmanager
def skill_span(run_id: str, trace_id: str, skill_name: str,
               skill_version: str = "1", request_id: str = "",
               agent_role: str = "", **kw):
    """Span for skill.<skill_name> (each Skill execution)."""
    name = "skill.%s" % skill_name
    attrs = {
        "mp.skill_name": skill_name,
        "mp.skill_version": skill_version,
    }
    if request_id:
        attrs["mp.request_id"] = request_id
    attrs.update(kw)
    with start_span(name, run_id=run_id, trace_id=trace_id,
                    agent_role=agent_role, **attrs) as span:
        yield span


@contextlib.contextmanager
def mcp_span(run_id: str, trace_id: str, correlation_id: str = "",
             endpoint: str = "", method: str = "", agent_role: str = "", **kw):
    """Span for mcp.upstream (each upstream Docker/GitHub API call)."""
    attrs = {}
    if correlation_id:
        attrs["mp.correlation_id"] = correlation_id
    if endpoint:
        attrs["mp.endpoint"] = endpoint
    if method:
        attrs["mp.method"] = method
    attrs.update(kw)
    with start_span("mcp.upstream", run_id=run_id, trace_id=trace_id,
                    agent_role=agent_role, **attrs) as span:
        yield span


# ---------------------------------------------------------------------------
# W3C traceparent propagation (HTTP header format)
# ---------------------------------------------------------------------------
#
# Format: version-trace_id-parent_id-trace_flags
#   version:    2 hex chars (always "00")
#   trace_id:   32 hex chars (lowercase)
#   parent_id:  16 hex chars (lowercase)
#   trace_flags: 2 hex chars ("00" = not sampled, "01" = sampled)
#
# We map the MergePilot SpanContext to/from this format so that spans can
# propagate across HTTP boundaries (Gateway → MCP) and back.

TRACEPARENT_HEADER = "traceparent"


def to_traceparent(ctx: SpanContext, sampled: bool = True) -> str:
    """Serialize a SpanContext to a W3C traceparent header value."""
    flags = "01" if sampled else "00"
    return "00-%s-%s-%s" % (ctx.trace_id, ctx.span_id, flags)


def from_traceparent(value: str, run_id: str = "") -> Optional[SpanContext]:
    """Parse a W3C traceparent header into a SpanContext.

    Returns None if the value is malformed (fail-closed: do not propagate
    a broken context).
    """
    if not value or not isinstance(value, str):
        return None
    parts = value.strip().split("-")
    if len(parts) != 4:
        return None
    _ver, trace_id, span_id, _flags = parts
    if len(trace_id) != 32 or len(span_id) != 16:
        return None
    try:
        int(trace_id, 16)
        int(span_id, 16)
    except ValueError:
        return None
    return SpanContext(trace_id=trace_id, span_id=span_id, run_id=run_id)


def inject_headers(headers: dict, ctx: SpanContext = None,
                   run_id: str = ""):
    """Inject traceparent + mp.run_id into an HTTP headers dict.

    Modifies ``headers`` in place and returns it. If no context is given,
    uses the current thread-local context.
    """
    ctx = ctx or get_current_context()
    if ctx is None:
        return headers
    headers[TRACEPARENT_HEADER] = to_traceparent(ctx)
    if run_id or ctx.run_id:
        headers["X-MP-Run-Id"] = run_id or ctx.run_id
    return headers


def extract_context(headers: dict, run_id: str = "") -> Optional[SpanContext]:
    """Extract a SpanContext from HTTP headers (traceparent + X-MP-Run-Id).

    Returns None if no valid traceparent is found.
    """
    tp = None
    for k, v in headers.items():
        if k.lower() == TRACEPARENT_HEADER:
            tp = v
            break
    if tp is None:
        return None
    # run_id from X-MP-Run-Id header or fallback
    for k, v in headers.items():
        if k.lower() == "x-mp-run-id":
            run_id = run_id or v
            break
    return from_traceparent(tp, run_id=run_id)


# ---------------------------------------------------------------------------
# OTLP HTTP exporter (sends spans to a local otelcol / compatible receiver)
# ---------------------------------------------------------------------------


class OTLPExporter:
    """Sends completed spans to an OTLP/HTTP receiver.

    Fail-closed: if the receiver is unreachable, the export is silently
    dropped (logged to stderr). Business logic is never blocked by export
    failures.
    """

    def __init__(self, endpoint: str = "http://localhost:4318/v1/traces",
                 timeout: float = 2.0):
        self.endpoint = endpoint
        self.timeout = timeout
        self._failed = 0
        self._sent = 0

    def export(self, span: SpanRecord):
        """Export a single span. Non-blocking on failure."""
        import urllib.request
        import urllib.error
        payload = json.dumps({
            "resourceSpans": [{
                "resource": {"attributes": [{
                    "key": "service.name",
                    "value": {"stringValue": "mergepilot"}
                }]},
                "scopeSpans": [{
                    "spans": [self._span_to_otlp(span)]
                }]
            }]
        }).encode("utf-8")
        try:
            req = urllib.request.Request(
                self.endpoint, data=payload,
                headers={"Content-Type": "application/json"},
                method="POST")
            urllib.request.urlopen(req, timeout=self.timeout)
            self._sent += 1
        except Exception:
            self._failed += 1

    def _span_to_otlp(self, span: SpanRecord):
        """Convert SpanRecord to OTLP JSON span format."""
        return {
            "traceId": span.trace_id,
            "spanId": span.span_id,
            "parentSpanId": span.parent_span_id or "",
            "name": span.name,
            "kind": "SPAN_KIND_INTERNAL",
            "startTimeUnixNano": str(int(span.start_time * 1e9)),
            "endTimeUnixNano": str(int((span.end_time or time.time()) * 1e9)),
            "status": {
                "code": 1 if span.status == "OK" else (2 if span.status == "ERROR" else 0),
            },
            "attributes": [
                {"key": k, "value": {"stringValue": str(v)}}
                for k, v in span.attributes.items()
            ],
        }


class DualCollector:
    """Sends spans to both InMemoryCollector (for tests) and OTLPExporter
    (for local otelcol). Fail-closed on exporter errors."""

    def __init__(self, memory: InMemoryCollector = None,
                 exporter: OTLPExporter = None):
        self.memory = memory or InMemoryCollector()
        self.exporter = exporter

    def add_span(self, span: SpanRecord):
        self.memory.add_span(span)
        if self.exporter is not None:
            try:
                self.exporter.export(span)
            except Exception:
                pass  # fail-closed
