#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""M6-A · OpenTelemetry instrumentation for MergePilot.

Provides span creation, context propagation, and redaction for the
Controller → Gateway → Skill → MCP vertical slice.

Design decisions:
- Uses the existing MergePilot correlation IDs (run_id, trace_id,
  correlation_id) as OTel span ATTRIBUTES — not replacing them.
- OTel trace_id/span_id are generated by the SDK; the MergePilot
  trace_id is carried as the ``mp.trace_id`` attribute for correlation
  with the existing DB audit schema.
- Sensitive fields (PATs, tokens, env secrets) are NEVER written to
  span attributes; a denylist is enforced.
- Fail-closed: if OTel export fails, the business logic continues
  (observability must not break the pipeline), but the error is logged
  to stderr and the span is dropped (not retried inline).
- No SLS backend — exports to a local in-memory collector for testing
  and to OTLP HTTP for production (configurable).

Span naming contract (frozen):
  controller.process_event    — wraps the top-level controller event loop
  gateway.call_tool           — wraps each Policy Gateway MCP call
  skill.<skill_name>          — wraps each Skill execution
  mcp.upstream                — wraps each upstream Docker/GitHub API call

Required attributes on ALL spans:
  mp.run_id          — the task run identifier
  mp.trace_id        — the MergePilot internal trace ID (NOT OTel trace_id)
  mp.agent_role      — reviewer | fixer | verifier | coordinator | manager

Conditional attributes (by span type):
  controller: mp.stage, mp.attempt, mp.event_type, mp.verdict
  gateway:    mp.correlation_id, mp.tool, mp.decision, mp.git_sha
  skill:      mp.skill_name, mp.skill_version, mp.request_id, mp.status
  mcp:        mp.correlation_id, mp.endpoint, mp.method, mp.status_code
"""
from __future__ import annotations

import contextlib
import json
import os
import sys
import time
import traceback
from typing import Any, Optional

# ---------------------------------------------------------------------------
# Sensitive-field denylist — NEVER write these to span attributes
# ---------------------------------------------------------------------------

SENSITIVE_KEY_PATTERNS = (
    "token", "secret", "password", "passwd", "pat", "api_key",
    "apikey", "credential", "private_key", "auth_token",
    "authorization", "cookie", "session",
)

SENSITIVE_VALUE_PATTERNS = (
    "ghp_", "ghs_", "gho_", "sk-", "AKIA", "xox",
    "LTAI", "AKID", "sk-ant", "Bearer ",
    "BEGIN RSA PRIVATE", "BEGIN OPENSSH PRIVATE",
)


def _is_sensitive_key(key: str) -> bool:
    kl = key.lower()
    return any(p in kl for p in SENSITIVE_KEY_PATTERNS)


def _is_sensitive_value(value: Any) -> bool:
    if not isinstance(value, str):
        return False
    v = value.lower()
    if any((p.lower() in v) or (p in value) for p in SENSITIVE_VALUE_PATTERNS):
        return True
    # Database DSN shape: scheme://user:password@host/... (any driver)
    if re.search(r"[a-z][a-z0-9+.\-]*://[^\s/:@]+:[^\s/@]+@", v):
        return True
    return False


def redact_attributes(attrs: dict) -> dict:
    """Return a copy of ``attrs`` with sensitive keys/values removed."""
    out = {}
    for k, v in attrs.items():
        if _is_sensitive_key(k):
            out[k] = "<redacted>"
        elif _is_sensitive_value(v):
            out[k] = "<redacted>"
        else:
            out[k] = v
    return out


# ---------------------------------------------------------------------------
# In-memory span collector (for local testing without OTLP backend)
# ---------------------------------------------------------------------------


class SpanRecord:
    """A single recorded span (OTel-compatible shape)."""

    __slots__ = ("trace_id", "span_id", "parent_span_id", "name",
                 "status", "start_time", "end_time", "attributes",
                 "events", "run_id", "links", "drop_reason")

    def __init__(self, trace_id, span_id, parent_span_id, name,
                 run_id, attributes=None, links=None):
        self.trace_id = trace_id
        self.span_id = span_id
        self.parent_span_id = parent_span_id
        self.name = name
        self.status = "OK"
        self.start_time = time.time()
        self.end_time = None
        self.run_id = run_id
        # PoC: async handoff links [{trace_id, span_id}]; drop_reason marks
        # spans whose redaction itself failed (never exported anywhere).
        self.links = list(links or [])
        self.drop_reason = None
        self.events = []
        try:
            self.attributes = redact_attributes(attributes or {})
        except Exception:
            self.attributes = {}
            self.drop_reason = "redaction_failed"

    def set_attribute(self, key, value):
        if self.drop_reason:
            return
        try:
            sensitive = _is_sensitive_key(key) or _is_sensitive_value(value)
        except Exception:
            self.drop_reason = "redaction_failed"
            return
        self.attributes[key] = "<redacted>" if sensitive else value

    def add_event(self, name, attributes=None):
        if self.drop_reason:
            return
        try:
            safe = redact_attributes(attributes or {})
        except Exception:
            self.drop_reason = "redaction_failed"
            return
        self.events.append({
            "name": name,
            "timestamp": time.time(),
            "attributes": safe,
        })

    def set_status(self, status):
        if status not in ("OK", "ERROR", "UNSET"):
            raise ValueError("span status must be OK/ERROR/UNSET")
        self.status = status

    def end(self):
        self.end_time = time.time()

    @property
    def duration_ms(self):
        if self.end_time:
            return round((self.end_time - self.start_time) * 1000, 2)
        return None

    def to_dict(self):
        d = {
            "trace_id": self.trace_id,
            "span_id": self.span_id,
            "parent_span_id": self.parent_span_id,
            "name": self.name,
            "status": self.status,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "duration_ms": self.duration_ms,
            "run_id": self.run_id,
            "attributes": dict(self.attributes),
            "events": list(self.events),
        }
        if self.links:
            d["links"] = [dict(l) for l in self.links]
        if self.drop_reason:
            d["drop_reason"] = self.drop_reason
        return d


# ---------------------------------------------------------------------------
# Export statistics (PoC): local telemetry export failure accounting.
# Telemetry is fail-open w.r.t. business but never silent about failure.
# ---------------------------------------------------------------------------

_EXPORT_STATS = {
    "sent": 0,
    "failed_export": 0,
    "dropped_export": 0,       # collector-level export errors
    "dropped_redaction": 0,    # spans discarded because redaction itself failed
}


def bump_export_stat(key: str, n: int = 1):
    if key in _EXPORT_STATS:
        _EXPORT_STATS[key] += n


def get_export_stats() -> dict:
    """Snapshot of local telemetry counters. Governance-safe: read-only."""
    return dict(_EXPORT_STATS)


class DualSLSCollector:
    """Dual-write collector: InMemoryCollector + SLSExporter.

    Spans are stored in memory (for test assertions) AND enqueued to
    an SLSExporter (for SLS trace export). The SLS export runs on a
    background thread and is fail-closed (never blocks the caller).

    Usage:
        sls_exporter = SLSExporter(config)
        sls_exporter.start()
        collector = DualSLSCollector(memory=InMemoryCollector(),
                                     sls_exporter=sls_exporter)
        set_collector(collector)
        # ... run instrumented code ...
        sls_exporter.stop()  # flush + join
    """

    def __init__(self, memory: InMemoryCollector = None, sls_exporter=None):
        self.memory = memory or InMemoryCollector()
        self.sls_exporter = sls_exporter

    def add_span(self, span: SpanRecord):
        # Memory store (always)
        self.memory.add_span(span)
        # SLS export (background, fail-closed)
        if self.sls_exporter is not None:
            try:
                self.sls_exporter.enqueue(span)
            except Exception:
                pass  # fail-closed: export failure never blocks business


class InMemoryCollector:
    """Collects spans in-process for testing. Thread-safe."""

    def __init__(self):
        self.spans = []
        self._lock = __import__("threading").Lock()

    def add_span(self, span: SpanRecord):
        with self._lock:
            self.spans.append(span)

    def clear(self):
        with self._lock:
            self.spans.clear()

    def get_by_run_id(self, run_id):
        with self._lock:
            return [s for s in self.spans if s.run_id == run_id]

    def get_by_name(self, name):
        with self._lock:
            return [s for s in self.spans if s.name == name]

    def to_json(self):
        with self._lock:
            return json.dumps([s.to_dict() for s in self.spans], indent=2)

    @property
    def count(self):
        with self._lock:
            return len(self.spans)


# ---------------------------------------------------------------------------
# Global collector (singleton) — set by tests; None = no collection
# ---------------------------------------------------------------------------

_global_collector: Optional[InMemoryCollector] = None


def set_collector(collector: Optional[InMemoryCollector]):
    global _global_collector
    _global_collector = collector


def get_collector() -> Optional[InMemoryCollector]:
    return _global_collector


# ---------------------------------------------------------------------------
# Span context + tracer
# ---------------------------------------------------------------------------

import hashlib
import random
import re


def _gen_span_id() -> str:
    return hashlib.sha256(os.urandom(16)).hexdigest()[:16]


def _gen_trace_id() -> str:
    return hashlib.sha256(os.urandom(16)).hexdigest()[:32]


class SpanContext:
    """Carries trace_id, span_id, and run_id across the call chain."""
    __slots__ = ("trace_id", "span_id", "run_id")

    def __init__(self, trace_id, span_id, run_id):
        self.trace_id = trace_id
        self.span_id = span_id
        self.run_id = run_id

    def child(self):
        return SpanContext(self.trace_id, _gen_span_id(), self.run_id)


# Thread-local current span context
import threading
_current_ctx = threading.local()


def get_current_context() -> Optional[SpanContext]:
    return getattr(_current_ctx, "ctx", None)


def _set_current_context(ctx: Optional[SpanContext]):
    if ctx is None:
        if hasattr(_current_ctx, "ctx"):
            del _current_ctx.ctx
    else:
        _current_ctx.ctx = ctx


@contextlib.contextmanager
def start_span(name: str, run_id: str = "", trace_id: str = "",
               agent_role: str = "", parent_span_id: str = None,
               links=None, **attributes):
    """Start a new span as a child of the current context (or root).

    PoC additions:
      - ``parent_span_id``: reattach a hop-root span to a producer span id
        carried over an async/HTTP boundary when no thread-local parent
        exists (cross-process rejoin on the same trace).
      - ``links``: list of {"trace_id","span_id"} dicts expressing async
        handoff (Span Link semantics); never fakes parenting.

    The span is automatically ended on context exit. If redaction itself
    fails, the span is marked ``drop_reason`` and is NOT exported anywhere,
    but the failure is counted locally.
    """
    parent = get_current_context()

    if trace_id and parent is None:
        # Root span — use provided trace_id
        ctx = SpanContext(trace_id, _gen_span_id(), run_id)
    elif parent is not None:
        # Child span — inherit trace_id from parent
        ctx = parent.child()
        if run_id and not ctx.run_id:
            ctx.run_id = run_id
    else:
        # No parent, no trace_id — generate both
        ctx = SpanContext(_gen_trace_id(), _gen_span_id(), run_id)

    effective_parent = parent.span_id if parent is not None else parent_span_id
    span = SpanRecord(
        trace_id=ctx.trace_id,
        span_id=ctx.span_id,
        parent_span_id=effective_parent,
        name=name,
        run_id=ctx.run_id,
        links=links,
    )

    # Set required attributes
    if run_id:
        span.set_attribute("mp.run_id", run_id)
    if trace_id or ctx.trace_id:
        span.set_attribute("mp.trace_id", trace_id or ctx.trace_id)
    if agent_role:
        span.set_attribute("mp.agent_role", agent_role)

    # Set extra attributes
    for k, v in attributes.items():
        span.set_attribute(k, v)

    _set_current_context(ctx)
    try:
        yield span
        if span.status == "UNSET":
            span.set_status("OK")
    except Exception as exc:
        span.set_status("ERROR")
        span.add_event("exception", {
            "type": type(exc).__name__,
            "message": str(exc)[:200],
            # NEVER include traceback (may contain secrets in env dumps)
        })
        raise
    finally:
        span.end()
        if getattr(span, "drop_reason", None) == "redaction_failed":
            bump_export_stat("dropped_redaction")
        elif _global_collector is not None:
            try:
                _global_collector.add_span(span)
            except Exception:
                pass  # fail-closed: observability must not break pipeline
        _set_current_context(parent)


# ---------------------------------------------------------------------------
# Convenience wrappers for the three required span types
# ---------------------------------------------------------------------------


@contextlib.contextmanager
def controller_span(run_id: str, trace_id: str, agent_role: str = "coordinator",
                    stage: str = "", attempt: int = 0, **kw):
    """Span for controller.process_event (the top-level event loop tick)."""
    attrs = {"mp.stage": stage, "mp.attempt": attempt}
    attrs.update(kw)
    with start_span("controller.process_event", run_id=run_id,
                    trace_id=trace_id, agent_role=agent_role, **attrs) as span:
        yield span


@contextlib.contextmanager
def gateway_span(run_id: str, trace_id: str, correlation_id: str = "",
                 tool: str = "", agent_role: str = "", **kw):
    """Span for gateway.call_tool (each Policy Gateway MCP call)."""
    attrs = {}
    if correlation_id:
        attrs["mp.correlation_id"] = correlation_id
    if tool:
        attrs["mp.tool"] = tool
    attrs.update(kw)
    with start_span("gateway.call_tool", run_id=run_id,
                    trace_id=trace_id, agent_role=agent_role, **attrs) as span:
        yield span


@contextlib.contextmanager
def skill_span(run_id: str, trace_id: str, skill_name: str,
               skill_version: str = "1", request_id: str = "",
               agent_role: str = "", **kw):
    """Span for skill.<skill_name> (each Skill execution)."""
    name = "skill.%s" % skill_name
    attrs = {
        "mp.skill_name": skill_name,
        "mp.skill_version": skill_version,
    }
    if request_id:
        attrs["mp.request_id"] = request_id
    attrs.update(kw)
    with start_span(name, run_id=run_id, trace_id=trace_id,
                    agent_role=agent_role, **attrs) as span:
        yield span


@contextlib.contextmanager
def mcp_span(run_id: str, trace_id: str, correlation_id: str = "",
             endpoint: str = "", method: str = "", agent_role: str = "", **kw):
    """Span for mcp.upstream (each upstream Docker/GitHub API call)."""
    attrs = {}
    if correlation_id:
        attrs["mp.correlation_id"] = correlation_id
    if endpoint:
        attrs["mp.endpoint"] = endpoint
    if method:
        attrs["mp.method"] = method
    attrs.update(kw)
    with start_span("mcp.upstream", run_id=run_id, trace_id=trace_id,
                    agent_role=agent_role, **attrs) as span:
        yield span


# ---------------------------------------------------------------------------
# W3C traceparent propagation (HTTP header format)
# ---------------------------------------------------------------------------
#
# Format: version-trace_id-parent_id-trace_flags
#   version:    2 hex chars (always "00")
#   trace_id:   32 hex chars (lowercase)
#   parent_id:  16 hex chars (lowercase)
#   trace_flags: 2 hex chars ("00" = not sampled, "01" = sampled)
#
# We map the MergePilot SpanContext to/from this format so that spans can
# propagate across HTTP boundaries (Gateway → MCP) and back.

TRACEPARENT_HEADER = "traceparent"


def to_traceparent(ctx: SpanContext, sampled: bool = True) -> str:
    """Serialize a SpanContext to a W3C traceparent header value."""
    flags = "01" if sampled else "00"
    return "00-%s-%s-%s" % (ctx.trace_id, ctx.span_id, flags)


def from_traceparent(value: str, run_id: str = "") -> Optional[SpanContext]:
    """Parse a W3C traceparent header into a SpanContext.

    Returns None if the value is malformed (fail-closed: do not propagate
    a broken context).
    """
    if not value or not isinstance(value, str):
        return None
    parts = value.strip().split("-")
    if len(parts) != 4:
        return None
    _ver, trace_id, span_id, _flags = parts
    if len(trace_id) != 32 or len(span_id) != 16:
        return None
    try:
        int(trace_id, 16)
        int(span_id, 16)
    except ValueError:
        return None
    return SpanContext(trace_id=trace_id, span_id=span_id, run_id=run_id)


def inject_headers(headers: dict, ctx: SpanContext = None,
                   run_id: str = ""):
    """Inject traceparent + mp.run_id into an HTTP headers dict.

    Modifies ``headers`` in place and returns it. If no context is given,
    uses the current thread-local context.
    """
    ctx = ctx or get_current_context()
    if ctx is None:
        return headers
    headers[TRACEPARENT_HEADER] = to_traceparent(ctx)
    if run_id or ctx.run_id:
        headers["X-MP-Run-Id"] = run_id or ctx.run_id
    return headers


def extract_context(headers: dict, run_id: str = "") -> Optional[SpanContext]:
    """Extract a SpanContext from HTTP headers (traceparent + X-MP-Run-Id).

    Returns None if no valid traceparent is found.
    """
    tp = None
    for k, v in headers.items():
        if k.lower() == TRACEPARENT_HEADER:
            tp = v
            break
    if tp is None:
        return None
    # run_id from X-MP-Run-Id header or fallback
    for k, v in headers.items():
        if k.lower() == "x-mp-run-id":
            run_id = run_id or v
            break
    return from_traceparent(tp, run_id=run_id)


# ---------------------------------------------------------------------------
# Matrix / task-text trace carrier (PoC)
# ---------------------------------------------------------------------------
#
# Async handoff across Matrix rooms cannot use HTTP headers, so the W3C
# traceparent rides inside the task message body as a single trailing line.
# Strictly validated on parse; anything malformed yields None (fail-closed):
# we never resume a broken context. The trailer contains only hex IDs and a
# run_id — no prompt/code/credential content ever travels in it.

_CARRIER_LINE = re.compile(
    r"\[MPTRACE\] v=1 tp=([0-9a-f]{2})-([0-9a-f]{32})-([0-9a-f]{16})-([0-9a-f]{2})"
    r" run=([A-Za-z0-9._\-]+)")


def append_task_carrier(task_text: str, ctx: SpanContext = None) -> str:
    """Append (or refresh) the trailing MPTRACE line for outgoing dispatches.

    Idempotent: any existing trailer line is stripped first. With no current
    context the text is returned unchanged.
    """
    ctx = ctx or get_current_context()
    if ctx is None:
        return task_text
    base = task_text.rstrip()
    base = base.split("\n[MPTRACE] ")[0].rstrip()
    flags = "01"
    return (base + "\n[MPTRACE] v=1 tp=00-%s-%s-%s run=%s\n"
            % (ctx.trace_id, ctx.span_id, flags, ctx.run_id))


def parse_task_carrier(task_text: str) -> Optional[SpanContext]:
    """Extract SpanContext from the last valid MPTRACE line, else None."""
    if not task_text or not isinstance(task_text, str):
        return None
    match = None
    for line in task_text.splitlines():
        m = _CARRIER_LINE.search(line.strip())
        if m:
            match = m
    if match is None:
        return None
    trace_id, span_id = match.group(2), match.group(3)
    return SpanContext(trace_id=trace_id, span_id=span_id,
                       run_id=match.group(5))


def make_link(ctx: SpanContext) -> dict:
    """Build one link record referencing a producer's SpanContext."""
    return {"trace_id": ctx.trace_id, "span_id": ctx.span_id}


# ---------------------------------------------------------------------------
# GenAI semantic builders (PoC, frozen attribute allowlist)
# ---------------------------------------------------------------------------

GENAI_ATTR_ALLOWLIST = {
    # input key -> exported span attribute key
    "run_id": "mp.run_id",
    "task_id": "mp.task_id",
    "agent_role": "mp.agent_role",
    "stage": "mp.stage",
    "attempt": "mp.attempt",
    "tool_name": "mp.tool_name",
    "tool_status": "mp.tool_status",
    "policy_decision": "mp.policy_decision",
    "finding_count": "mp.finding_count",
    "final_decision": "mp.final_decision",
    "verification_status": "mp.verification_status",
    "human_intervention": "mp.human_intervention",
    "model_provider": "gen_ai.system",
    "model_name": "gen_ai.request.model",
    "token_usage": "gen_ai.usage",
    "duration_ms": "mp.duration_ms",
}

GENAI_PROMPT_CAPTURE_DEFAULT_OFF = True  # content capture forbidden this round


def build_genai_attrs(**kw) -> dict:
    """Filter+map caller attributes down to the frozen allowlist."""
    out = {}
    for k, v in kw.items():
        mapped = GENAI_ATTR_ALLOWLIST.get(k)
        if mapped is not None and v is not None:
            out[mapped] = v
    return out


@contextlib.contextmanager
def entry_span(name: str, run_id: str, attrs: dict = None):
    """Root 'Entry' span for one MergePilot business run (e.g. pr_review)."""
    clean = build_genai_attrs(**(attrs or {}))
    with start_span(name, run_id=run_id, agent_role="manager", **clean) as sp:
        yield sp


class AgentWindowSpan:
    """Manually-opened Agent/Stage window span (dispatch → completion).

    Spans a controller observation window across events, so it cannot use a
    with-block. Holds the thread-local context while open so same-process
    children still attach correctly; restores the previous context on close.
    """

    def __init__(self, name: str, run_id: str, trace_id: str,
                 agent_role: str = "", stage: str = "", attempt: int = 0,
                 attrs: dict = None):
        self._prev = get_current_context()
        clean_attrs = build_genai_attrs(**(attrs or {}))
        self.span = SpanRecord(
            trace_id=trace_id or (self._prev.trace_id if self._prev else _gen_trace_id()),
            span_id=_gen_span_id(),
            parent_span_id=self._prev.span_id if self._prev else None,
            name=name,
            run_id=run_id,
        )
        if run_id:
            self.span.set_attribute("mp.run_id", run_id)
        if agent_role:
            self.span.set_attribute("mp.agent_role", agent_role)
        if stage:
            self.span.set_attribute("mp.stage", stage)
        self.span.set_attribute("mp.attempt", attempt)
        for k, v in clean_attrs.items():
            self.span.set_attribute(k, v)
        self.ctx = SpanContext(self.span.trace_id, self.span.span_id, run_id)
        _set_current_context(self.ctx)

    def finish(self, final_decision: str = "", verification_status: str = "",
               human_intervention: bool = False) -> None:
        for k, v in (("final_decision", final_decision),
                     ("verification_status", verification_status),
                     ("human_intervention", human_intervention)):
            mapped = GENAI_ATTR_ALLOWLIST.get(k)
            if mapped is not None:
                self.span.set_attribute(mapped, v)
        self._close("OK")

    def fail(self) -> None:
        self._close("ERROR")

    def _close(self, status: str) -> None:
        try:
            self.span.set_status(status)
        finally:
            self.span.end()
            if getattr(self.span, "drop_reason", None) == "redaction_failed":
                bump_export_stat("dropped_redaction")
            elif _global_collector is not None:
                try:
                    _global_collector.add_span(self.span)
                except Exception:
                    pass
            _set_current_context(self._prev)





# ---------------------------------------------------------------------------
# OTLP/HTTP protobuf encoding (AgentLoop ingestion is http/protobuf ONLY;
# official docs: "仅支持 HTTP/Protobuf，暂不支持 HTTP/JSON 和 gRPC").
# Hand-rolled minimal writer for the subset this codebase emits — no external
# dependency. Wire format reference: opentelemetry/proto/trace/v1.
# ---------------------------------------------------------------------------

def _pb_varint(n: int) -> bytes:
    out = bytearray()
    while True:
        b = n & 0x7F
        n >>= 7
        out.append(b | (0x80 if n else 0))
        if not n:
            return bytes(out)


def _pb_tag(field: int, wire: int) -> bytes:
    return _pb_varint((field << 3) | wire)


def _pb_len(field: int, payload: bytes) -> bytes:
    return _pb_tag(field, 2) + _pb_varint(len(payload)) + payload


def _pb_uint64_fixed(field: int, n: int) -> bytes:
    import struct
    return _pb_tag(field, 1) + struct.pack("<Q", n)


def _pb_kv(k: str, v: Any) -> bytes:
    # KeyValue{1: key, 2: AnyValue{1: string_value}}
    return _pb_len(1, k.encode()) + _pb_len(2, _pb_len(1, str(v).encode()))


_STATUS_CODE = {"OK": 1, "ERROR": 2}          # else UNSET=0
_SPAN_KIND_INTERNAL = 1                        # enum SpanKind


def span_to_otlp_proto(span: SpanRecord, service_name: str,
                       resource_attrs: dict = None) -> bytes:
    """Encode one SpanRecord as ExportTraceServiceRequest bytes."""
    # SDK identity defaults (honest: our own emitter, not LoongSuite probe);
    # OTEL_RESOURCE_ATTRIBUTES values take precedence over defaults.
    merged = {
        "telemetry.sdk.name": "mergepilot-otel",
        "telemetry.sdk.language": "python",
        "telemetry.sdk.version": "1",
    }
    merged.update(resource_attrs or {})
    kvs = [_pb_kv("service.name", service_name)]
    for k, v in merged.items():
        kvs.append(_pb_kv(k, v))
    resource = b"".join(_pb_len(1, x) for x in kvs)

    scope = _pb_len(1, b"mergepilot-otel") + _pb_len(2, b"1")
    t0 = int(span.start_time * 1e9)
    t1 = int((span.end_time or time.time()) * 1e9)
    parts = [
        _pb_len(1, bytes.fromhex(span.trace_id)),
        _pb_len(2, bytes.fromhex(span.span_id)),
    ]
    if span.parent_span_id:
        parts.append(_pb_len(4, bytes.fromhex(span.parent_span_id)))
    parts.append(_pb_len(5, span.name.encode()))
    parts.append(_pb_tag(6, 0) + _pb_varint(_SPAN_KIND_INTERNAL))
    parts.append(_pb_uint64_fixed(7, t0))
    parts.append(_pb_uint64_fixed(8, t1))
    for k, v in span.attributes.items():
        parts.append(_pb_len(9, _pb_kv(k, v)))
    for link in getattr(span, "links", []) or []:
        lm = _pb_len(1, bytes.fromhex(link["trace_id"])) + \
            _pb_len(2, bytes.fromhex(link["span_id"]))
        parts.append(_pb_len(11, lm))
    code = _STATUS_CODE.get(span.status, 0)
    parts.append(_pb_len(15, _pb_tag(3, 0) + _pb_varint(code)))
    span_msg = b"".join(parts)

    scope_spans = _pb_len(1, scope) + _pb_len(2, span_msg)
    resource_spans = _pb_len(1, resource) + _pb_len(2, scope_spans)
    return _pb_len(1, resource_spans)


def parse_resource_attributes(environ=None) -> dict:
    """Official OTEL_RESOURCE_ATTRIBUTES (k1=v1,k2=v2, URL-decoded)."""
    from urllib.parse import unquote
    raw = (environ if environ is not None else os.environ) \
        .get("OTEL_RESOURCE_ATTRIBUTES", "")
    out = {}
    for pair in raw.split(","):
        pair = pair.strip()
        if not pair or "=" not in pair:
            continue
        k, _, v = pair.partition("=")
        if k.strip():
            try:
                out[k.strip()] = unquote(v.strip())
            except Exception:
                out[k.strip()] = v.strip()
    return out


class OTLPExporter:
    """Sends completed spans to an OTLP/HTTP receiver.

    Fail-closed: if the receiver is unreachable, the export is silently
    dropped (logged to stderr). Business logic is never blocked by export
    failures.
    """

    def __init__(self, endpoint: str = "http://localhost:4318/v1/traces",
                 timeout: float = 2.0, headers: dict = None,
                 fmt: str = "json"):
        self.endpoint = endpoint
        self.timeout = timeout
        # AgentLoop ingestion is http/protobuf only; json kept for local
        # otelcol receivers and backward compatibility.
        self._format = fmt if fmt in ("json", "proto") else "json"
        # Auth/license headers ride on every export POST; their VALUES are
        # never logged, counted into stats, or exposed via repr/str paths.
        self._headers = dict(headers or {})
        self._failed = 0
        self._sent = 0
        # Telemetry must never be hijacked by ambient system proxies and must
        # not pay opener-construction cost per span.
        import urllib.request as _rq
        self._opener = _rq.build_opener(_rq.ProxyHandler({}))

    @staticmethod
    def headers_from_standard_env(environ=None) -> dict:
        """Parse OTEL_EXPORTER_OTLP_HEADERS (official OTel spec name).

        Format: ``key1=value1,key2=value2`` (URL-decoded per spec). Returns {}
        when unset/malformed-pair-wise — malformed pairs are skipped, keys are
        not invented by this codebase.
        """
        from urllib.parse import unquote
        raw = (environ if environ is not None else os.environ) \
            .get("OTEL_EXPORTER_OTLP_HEADERS", "")
        out = {}
        for pair in raw.split(","):
            pair = pair.strip()
            if not pair or "=" not in pair:
                continue
            k, _, v = pair.partition("=")
            k, v = k.strip(), v.strip()
            if k:
                try:
                    out[k] = unquote(v)
                except Exception:
                    out[k] = v
        return out

    def export(self, span: SpanRecord):
        """Export a single span. Non-blocking on failure."""
        import urllib.error
        # Official env (OTEL_SERVICE_NAME) wins over legacy MP_SERVICE_NAME.
        service_name = os.environ.get("OTEL_SERVICE_NAME") or \
            os.environ.get("MP_SERVICE_NAME", "mergepilot")
        if self._format == "proto":
            payload = span_to_otlp_proto(
                span, service_name,
                resource_attrs=parse_resource_attributes())
            content_type = "application/x-protobuf"
        else:
            content_type = "application/json"
            payload = json.dumps({
            "resourceSpans": [{
                "resource": {"attributes": [{
                    "key": "service.name",
                    "value": {"stringValue": service_name}
                }]},
                "scopeSpans": [{
                    "spans": [self._span_to_otlp(span)]
                }]
            }]
        }).encode("utf-8")
        try:
            from urllib.request import Request
            req_headers = dict(self._headers)
            req_headers["Content-Type"] = content_type
            req = Request(self.endpoint, data=payload,
                          headers=req_headers, method="POST")
            self._opener.open(req, timeout=self.timeout)
            self._sent += 1
            bump_export_stat("sent")
        except Exception:
            self._failed += 1
            bump_export_stat("failed_export")

    def _span_to_otlp(self, span: SpanRecord):
        """Convert SpanRecord to OTLP JSON span format."""
        otlp = {
            "traceId": span.trace_id,
            "spanId": span.span_id,
            "parentSpanId": span.parent_span_id or "",
            "name": span.name,
            "kind": "SPAN_KIND_INTERNAL",
            "startTimeUnixNano": str(int(span.start_time * 1e9)),
            "endTimeUnixNano": str(int((span.end_time or time.time()) * 1e9)),
            "status": {
                "code": 1 if span.status == "OK" else (2 if span.status == "ERROR" else 0),
            },
            "attributes": [
                {"key": k, "value": {"stringValue": str(v)}}
                for k, v in span.attributes.items()
            ],
        }
        if getattr(span, "links", None):
            otlp["links"] = [
                {"traceId": l.get("trace_id", ""), "spanId": l.get("span_id", "")}
                for l in span.links
            ]
        return otlp


class DualCollector:
    """Sends spans to both InMemoryCollector (for tests) and OTLPExporter
    (for local otelcol). Fail-closed on exporter errors."""

    def __init__(self, memory: InMemoryCollector = None,
                 exporter: OTLPExporter = None):
        self.memory = memory or InMemoryCollector()
        self.exporter = exporter

    def add_span(self, span: SpanRecord):
        self.memory.add_span(span)
        drop = getattr(span, "drop_reason", None)
        if drop == "redaction_failed":
            # Redaction itself failed → span must not reach any external sink.
            bump_export_stat("dropped_redaction")
            return
        if self.exporter is None:
            return
        try:
            self.exporter.export(span)
        except Exception:
            bump_export_stat("dropped_export")  # fail-closed; counted locally
