#!/bin/bash
# m3b-b4c0-controller.sh — B4c-0.3 controller hardening 验收(set -euo pipefail + 证据直接入仓库 + 故障注入回滚)。
# 覆盖:sha256 parity / L2-on startup(无 token)/ 非法开关失败 / L2=off 维护持久化 run /
#       预检失败不替换 / **预检过但正式启动失败→恢复原容器原配置(同 container ID)** / 凭证扫描。
# 必须成功的命令(部署/插入/恢复)显式断言返回码;预期失败用 if/set +e 捕获 rc。
# 依赖:keeper 在跑;audit-pg/policy-gw 在跑;migration 已应用。
set -euo pipefail
EV=/mnt/d/goai/mergepilot-os/evidence/m3b-b4c/0-controller
mkdir -p "$EV"
rm -f "$EV"/*.txt "$EV"/*.out 2>/dev/null || true   # 测试前清空 evidence(防累积/漂移)
OUT="$EV/controller-test.out"
: > "$OUT"
log(){ echo "$*" | tee -a "$OUT"; }
PASS=0; FAIL=0
ok(){ log "  ✅ $1"; PASS=$((PASS+1)); }
bad(){ log "  ❌ $1"; FAIL=$((FAIL+1)); }

DIR=/home/ngh/.config/mergepilot
CTRL="$DIR/controller.env"
PG_SU=$(grep '^PG_USER=' "$CTRL" | cut -d= -f2- | tr -d '"'\''[:space:]'); PG_SU=${PG_SU:-mergepilot}
PG_DB=$(grep '^PG_DATABASE=' "$CTRL" | cut -d= -f2- | tr -d '"'\''[:space:]'); PG_DB=${PG_DB:-mergepilot_audit}
SU_PW=$(grep '^PG_PASS=' "$CTRL" | head -1 | cut -d= -f2- | tr -d '"'\''[:space:]')
PSQL(){ docker exec -e PGPASSWORD="$SU_PW" audit-pg psql -U "$PG_SU" -d "$PG_DB" -t -A -c "$1" 2>/dev/null; }
START=/mnt/d/goai/mergepilot-os/tools/start-controller-container.sh
REAL_CTX=/mnt/d/goai/mergepilot-os/tools/workflow-controller
NAME=mergepilot-controller

# trap:中断/退出时清测试 run + 恢复 controller L2=off(用真实 BUILD_CTX)
cleanup(){
  set +e
  PSQL "DELETE FROM task_runs WHERE run_id LIKE 'b4c0%persist%';" >/dev/null 2>&1
  BUILD_CTX="$REAL_CTX" L2_MERGE_ENABLED=0 bash "$START" >/dev/null 2>&1
  log "[cleanup] 测试 run 清理 + controller 恢复 L2=off"
}
trap cleanup EXIT

log "═══════════════════════════════════════════════"
log "  B4c-0.3 controller hardening 验收"
log "═══════════════════════════════════════════════"
for i in $(seq 1 30); do docker exec audit-pg pg_isready -U "$PG_SU" -d "$PG_DB" >/dev/null 2>&1 && break; sleep 2; done

# ─── baseline:恢复 controller 到已知 L2=off 状态 ───
log ""; log "=== baseline: restore controller L2=off (必须成功) ==="
if BUILD_CTX="$REAL_CTX" L2_MERGE_ENABLED=0 bash "$START" >>"$OUT" 2>&1; then ok "baseline L2=off 部署成功"; else bad "baseline 部署失败"; exit 1; fi

# ─── 1. sha256 parity(现哈希,直接落 evidence)───
log ""; log "=== 1. 源码 sha256 parity(mergepilot-os ↔ tools) ==="
{
  echo "## B4c-0.3 source parity — generated by m3b-b4c0-controller.sh(终稿后跑,不再改脚本)"
  for rel in workflow-controller/controller.py workflow-controller/gateway_client.py workflow-controller/Dockerfile start-controller-container.sh m3a-verify.sh audit-db/m3b_b4c.sql m3b-b4c0-migration.sh m3b-b4c0-controller.sh; do
    a=$(sha256sum "/mnt/d/goai/mergepilot-os/tools/$rel" 2>/dev/null | cut -c1-16)
    b=$(sha256sum "/mnt/d/goai/tools/$rel" 2>/dev/null | cut -c1-16)
    echo "  $rel  mergepilot-os=$a  tools=$b  $([ "$a" = "$b" ] && echo OK || echo DRIFT)"
  done
} > "$EV/source-parity.txt"
cat "$EV/source-parity.txt" | tee -a "$OUT" | grep -q DRIFT && bad "parity 漂移(见 source-parity.txt)" || ok "8 文件 parity 全一致"

# ─── 2. build + L2-on startup(无 token)───
log ""; log "=== 2. build + start L2-on(必须成功) ==="
if BUILD_CTX="$REAL_CTX" L2_MERGE_ENABLED=1 bash "$START" >>"$OUT" 2>&1; then ok "L2-on 部署成功"; else bad "L2-on 部署失败"; exit 1; fi
docker logs "$NAME" 2>&1 | grep -E "L2_MERGE_ENABLED=on|未终结审批|login OK|启动" | head -6 > "$EV/controller-l2on-logs.txt"
grep -q "L2_MERGE_ENABLED=on;未终结审批" "$EV/controller-l2on-logs.txt" && ok "L2-on startup_assert 过" || bad "L2-on startup 未过"
LEAK=$(docker logs "$NAME" 2>&1 | grep -cE "token=[A-Za-z0-9]{8}|Bearer [A-Za-z0-9]" || true)
[ "${LEAK:-0}" = "0" ] && ok "日志无 token 泄漏" || bad "日志泄漏 token($LEAK 处)"

# ─── 3. 非法开关 → startup 失败 ───
log ""; log "=== 3. 非法 L2_MERGE_ENABLED=maybe → 启动失败(预期失败) ==="
docker rm -f "${NAME}-invalidtest" >/dev/null 2>&1 || true
set +e
docker run --rm --network hiclab-net --env-file "$CTRL" \
  -e PG_HOST=audit-pg -e PG_DATABASE=mergepilot_audit -e PG_USER=mergepilot \
  -e MATRIX_HS=http://hiclaw-controller:6167 -e GATEWAY_URL=http://policy-gw:8083 \
  -e COORDINATOR_TOKEN=dummy -e L2_MERGE_ENABLED=maybe --name "${NAME}-invalidtest" \
  mergepilot-controller:latest > "$EV/controller-invalid-flag.txt" 2>&1
INV_RC=$?
set -e
log "  invalid-flag rc=$INV_RC (expect non-zero)"
grep -q "FATAL: L2_MERGE_ENABLED='maybe' 非法" "$EV/controller-invalid-flag.txt" && ok "非法开关 → FATAL" || bad "非法开关应 FATAL"

# ─── 4. L2=off + 持久化 run → 仍被维护 ───
log ""; log "=== 4. L2=off 维护已持久化 approval_required run ==="
PSQL "DELETE FROM task_runs WHERE run_id LIKE 'b4c0%persist%';" >/dev/null
PSQL "INSERT INTO task_runs(run_id,status,repo,pr_number,current_stage,approval_required,verdict) VALUES('b4c03-persist-run','APPROVAL_PENDING','nghqqa/MergePilot',99999,'l2_binding',TRUE,'PASS');" >/dev/null
[ "$(PSQL "SELECT count(*) FROM task_runs WHERE run_id='b4c03-persist-run';")" = "1" ] && ok "测试 run 已插入" || { bad "测试 run 插入失败"; exit 1; }
if BUILD_CTX="$REAL_CTX" L2_MERGE_ENABLED=0 bash "$START" >>"$OUT" 2>&1; then ok "L2=off 部署成功"; else bad "L2=off 部署失败"; exit 1; fi
STARTUP_OFF=$(docker logs "$NAME" 2>&1 | grep "未终结审批" | tail -1)
echo "$STARTUP_OFF" | tee -a "$OUT"
echo "$STARTUP_OFF" | grep -q "未终结审批 run=1" && ok "L2=off 检测到待维护 run" || bad "L2=off 未检测待维护 run"
log "  wait 45s for ≥1 full tick..."
sleep 45
docker logs "$NAME" 2>&1 | grep "L2-stub" | tail -4 > "$EV/controller-l2off-maintains-run.txt"
cat "$EV/controller-l2off-maintains-run.txt" | tee -a "$OUT"
grep -q "initiate_l2_pending: 1 个 run 待绑定" "$EV/controller-l2off-maintains-run.txt" && ok "L2=off stub 仍扫描持久化 run" || bad "L2=off 未维护持久化 run"

# ─── 5. 预检失败不替换(非法开关触发 preflight 失败)───
log ""; log "=== 5. 预检失败 → 不替换健康容器 ==="
CID_BEFORE=$(docker inspect -f '{{.Id}}' "$NAME" 2>/dev/null || echo "")
set +e
L2_MERGE_ENABLED=maybe BUILD_CTX="$REAL_CTX" bash "$START" > "$EV/controller-preflight-gate.txt" 2>&1
PFG_RC=$?
set -e
log "  preflight-gate start-script rc=$PFG_RC (expect non-zero)"
CID_AFTER=$(docker inspect -f '{{.Id}}' "$NAME" 2>/dev/null || echo "")
log "  cid_before=${CID_BEFORE:0:12} cid_after=${CID_AFTER:0:12}"
[ "$PFG_RC" -ne 0 ] && ok "预检失败脚本非零退出" || bad "预检失败应非零退出"
[ "$CID_BEFORE" = "$CID_AFTER" ] && [ -n "$CID_BEFORE" ] && ok "预检失败:健康容器未替换" || bad "预检失败:容器被替换(门失效)"

# ─── 6. 故障注入:预检过、正式启动失败 → 恢复原容器原配置(P1-1)───
log ""; log "=== 6. 故障注入:preflight 过但 run_forever 失败 → 恢复原容器(同 ID) ==="
ORIG_CID=$(docker inspect -f '{{.Id}}' "$NAME" 2>/dev/null || echo "")
log "  原容器 cid=${ORIG_CID:0:12}"
# 造 broken BUILD_CTX:controller 在 startup_assert 后(非 CHECK 模式)sys.exit(1)→ 容器退出 → health 失败
BROKEN=/tmp/b4c-broken-ctx
rm -rf "$BROKEN"; mkdir -p "$BROKEN"
cp "$REAL_CTX/Dockerfile" "$BROKEN/Dockerfile"
cp "$REAL_CTX/gateway_client.py" "$BROKEN/gateway_client.py"
# 在 controller.py 的 run_forever() 调用前注入 sys.exit(1)(STARTUP_CHECK_ONLY 模式仍 exit 0,故 preflight 过)
python3 - "$REAL_CTX/controller.py" "$BROKEN/controller.py" <<'PY'
import sys
src = open(sys.argv[1]).read()
# 在 "    run_forever()" 前注入故障(仅非 CHECK 模式触发)
inject = '    print("[ctrl] FAULT-INJECT: exit 1 before run_forever (simulating post-startup failure)"); sys.exit(1)\n    run_forever()'
assert "    run_forever()" in src, "run_forever anchor not found"
src = src.replace("    run_forever()", inject, 1)
open(sys.argv[2], "w").write(src)
PY
[ -f "$BROKEN/controller.py" ] && ok "broken ctx 已构造(preflight 过、run_forever 前 exit 1)" || { bad "broken ctx 构造失败"; exit 1; }
set +e
BUILD_CTX="$BROKEN" L2_MERGE_ENABLED=0 bash "$START" > "$EV/controller-fault-rollback.txt" 2>&1
FAULT_RC=$?
set -e
log "  fault-injection start-script rc=$FAULT_RC (expect non-zero)"
RESTORED_CID=$(docker inspect -f '{{.Id}}' "$NAME" 2>/dev/null || echo "")
RUNNING=$(docker inspect -f '{{.State.Running}}' "$NAME" 2>/dev/null || echo false)
log "  restored cid=${RESTORED_CID:0:12} running=$RUNNING (orig=${ORIG_CID:0:12})"
cat "$EV/controller-fault-rollback.txt" | grep -E "FAULT-INJECT|回滚到原容器|未达 healthy" | tee -a "$OUT" | head -4
[ "$FAULT_RC" -ne 0 ] && ok "故障注入:正式启动失败脚本非零退出" || bad "故障注入应非零退出"
[ "$RESTORED_CID" = "$ORIG_CID" ] && [ -n "$ORIG_CID" ] && ok "故障注入:恢复的是原容器(同 container ID=原配置)" || bad "故障注入:未恢复原容器(restored=$RESTORED_CID orig=$ORIG_CID)"
[ "$RUNNING" = "true" ] && ok "原容器恢复后 running" || bad "原容器恢复后未 running"
grep -q "回滚到原容器" "$EV/controller-fault-rollback.txt" && ok "回滚日志确认(原配置 via rename+start)" || bad "缺回滚日志"

# ─── 7. 凭证扫描(全 evidence)───
log ""; log "=== 7. 凭证扫描(B4c evidence 全目录) ==="
set +e
grep -rniE "token=[A-Za-z0-9]{8}|Bearer [A-Za-z0-9]{8}|PG_PASS=[A-Za-z]|sk-live|access_token" /mnt/d/goai/mergepilot-os/evidence/m3b-b4c/ > "$EV/credential-scan.txt" 2>/dev/null
GREP_RC=$?
set -e
if [ "$GREP_RC" -ne 0 ]; then : > "$EV/credential-scan.txt"; ok "无凭证泄漏(grep 无匹配)"; else bad "凭证泄漏(见 credential-scan.txt)"; fi

# ─── 恢复 controller 到 L2=off(cleanup trap 也会再做一次)───
log ""; log "=== restore controller to L2=off ==="
if BUILD_CTX="$REAL_CTX" L2_MERGE_ENABLED=0 bash "$START" >>"$OUT" 2>&1; then ok "恢复 L2=off 成功"; else bad "恢复 L2=off 失败"; fi
PSQL "DELETE FROM task_runs WHERE run_id LIKE 'b4c0%persist%';" >/dev/null 2>&1 || true

log ""
log "═══════════════════════════════════════════════"
log "  B4c-0.3 controller 验收: PASS=$PASS FAIL=$FAIL"
log "═══════════════════════════════════════════════"
log "evidence → $EV"
trap - EXIT   # 已显式恢复,解除 trap(避免 cleanup 再跑一次部署)
[ "$FAIL" -eq 0 ] || exit 1
